services:
    app:
        build: .
        container_name: laravel_app
        volumes:
            - storage_volume:/var/www/html/storage
        ports:
            - "8080:80"
        depends_on:
            postgres:
                condition: service_healthy
            redis:
                condition: service_healthy
        environment:
            APP_NAME: "Listify"
            APP_DEBUG: false
            DB_CONNECTION: pgsql
            DB_HOST: postgres
            DB_PORT: 5432
            DB_DATABASE: laravel_db
            DB_USERNAME: laravel_user
            DB_PASSWORD: laravel_pass
            QUEUE_CONNECTION: sync
            CACHE_STORE: redis
            SESSION_DRIVER: redis
            REDIS_HOST: redis
            REDIS_PASSWORD: null
            REDIS_PORT: 6379
            MAIL_MAILER: smtp
            MAIL_HOST: mailhog
            MAIL_PORT: 1025
            MAIL_USERNAME: null
            MAIL_PASSWORD: null
            MAIL_ENCRYPTION: null
            MAIL_FROM_ADDRESS: example@example.com
            MAIL_FROM_NAME: "Listify"

    postgres:
        image: postgres:13
        container_name: laravel_postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: laravel_db
            POSTGRES_USER: laravel_user
            POSTGRES_PASSWORD: laravel_pass
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U laravel_user -d laravel_db" ]
            interval: 10s
            timeout: 5s
            retries: 5

    redis:
        image: redis:6-alpine
        container_name: laravel_redis
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            interval: 10s
            timeout: 5s
            retries: 5

    mailhog:
        image: mailhog/mailhog
        container_name: laravel_mailhog
        ports:
            - "8026:8025"

#    frontend:
#        build:
#            context: .
#            dockerfile: Dockerfile.frontend
#            args:
#                REPO_URL: https://github.com/talhafakhar/task-list-react.git
#        ports:
#            - "3000:3000"
#        environment:
#            REACT_APP_API_URL: http://localhost/api/
#        depends_on:
#            -   app

volumes:
    postgres_data:
    storage_volume:

networks:
    default:
